MODULE ALOCAVEIS
IMPLICIT NONE
	
REAL*8,DIMENSION(:),ALLOCATABLE::X,Y
INTEGER,DIMENSION(:),ALLOCATABLE::NO,C,CA,NOPRES
REAL*8,DIMENSION(:,:),ALLOCATABLE::VPRES
INTEGER,DIMENSION(:,:),ALLOCATABLE::TIPOPRES

END MODULE ALOCAVEIS