   
!##################################################################################
!Subrotina para abrir o arquivo de saida e gravar a hora inicial
!##################################################################################
SUBROUTINE OPEN_OUTPUT(ARQS,MON)
IMPLICIT NONE

CHARACTER*20:: ARQS
INTEGER::MON
INTEGER  IANO,IMES,IDIA,IHORA,IMIN,ISEC,I100TH

CALL GETDAT(IANO,IMES,IDIA)
CALL GETTIM(IHORA,IMIN,ISEC,I100TH)

WRITE(2,30)IDIA,IMES,IANO,IHORA,IMIN,ISEC
30 FORMAT(/,5X,74('*'),/,2(5X,1H*,72X,1H*,/),5X,1H*,18X, 'ANALISE NAO-LINEAR DE PLACAS ESPESSAS',&
   17X,1H*,/,5X,1H*,72X,1H*,/,5X, 1H*,20X,'MESHLESS LOCAL PETROV-GALERKIN',20X,1H*,/, 2(5X,1H*, 72X,&
     1H*,/),5X,74('*'),/,5X,1H*,52X,1H*,19X,1H*,/, 5X,1H*,52X, 1H*,2X,'DATA: ',I2.2,1H-,I2.2,1H-,&
      I4.4,1X,1H*,/,5X,1H*,16X, 'DANILO HIROSHI KONDA',16X,1H*,19X,1H*,/,5X,1H*,52X, 1H*,2X,'HORA: ',&
      I2.2,1H:,I2.2,1H:,I2.2,3X,1H*,/,5X,1H*, 52X, 1H*,19X,1H*,/,5X,74('*'),//,5X,'DESCRICAO DO PROBLEMA')
   
IF(MON.EQ.1)THEN
	WRITE(2,32) 
32 FORMAT (//,10X,'APROXIMACAO LINEAR')
ELSE IF(MON.EQ.2) THEN
	WRITE(2,34) 
34 FORMAT (//,10X,'APROXIMACAO QUADRATICA')
ELSE IF(MON.EQ.3) THEN
	WRITE(2,36) 
36 FORMAT (//,10X,'APROXIMACAO CUBICA')
ELSE
	WRITE(*,*) 'ERRO NA ESCOLHA DA APROXIMACAO'
	READ(*,*)
	STOP
ENDIF


RETURN
ENDSUBROUTINE OPEN_OUTPUT
    